# Global values to keep while the program is running
class GlobalValues:

    buttons_height_diff = 50
    buttons_width_diff = 139
    button_loc_1 = None
    button_loc_2 = None
    button_loc_3 = None
    button_loc_4 = None
    button_loc_bag_left = None
    button_loc_bag_right = None
    button_loc_bag_use_item = None
    pokemon_count = 649
    key_left = 'a'
    key_right = 'd'
    key_up = 'w'
    key_down = 's'
    settings = None
    pokemon_name_loc_x = None
    pokemon_name_loc_y = None
    pokemon_name_rec_width = 287
    pokemon_name_rec_height = 27
    pokemon_name_distance_x = 353
    pokemon_name_distance_y = -345
    pokemon_names = {}
    pokemon_encounters = {}
    pokemon_hp_loc_x = None
    pokemon_hp_loc_y = None
    pokemon_hp_rec_width = 165
    pokemon_hp_rec_height = 21
    pokemon_hp_distance_x = 430
    pokemon_hp_distance_y = -57
    bag_use_item_distance_x = 176
    bag_right_distance_x = 140
    bag_right_distance_y = 0
    skill1_keys = ["1", "1"]
    skill2_keys = ["1", "2"]
    skill3_keys = ["1", "3"]
    skill4_keys = ["1", "4"]
    skillrun_keys = ["4"]
    encountered_pokemon = "Unknown"
    encountered_pokemon_id = -1
    encountered_pokemon_image = None
